FROM php:7.4-fpm-alpine
WORKDIR /app
COPY composer.json  ./
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
RUN docker-php-ext-install bcmath
RUN composer install
COPY ./src ./src
COPY ./input.csv ./input.csv
COPY ./script.php ./script.php
COPY ./.env ./.env
COPY ./phpunit.xml.dist ./phpunit.xml.dist
CMD ["php-fpm", "-F"]